const produtos = [

//Harbinger

{
    id: '1',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Branco ',
    value: '',
},
{
    id: '2',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Preto',
    value: '',
},
{
    id: '3',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Azul ',
    value: '',
},
{
    id: '4',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Rosa',
    value: '',
},
{
    id: '5',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Vermelho ',
    value: '',
},
{
    id: '6',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Amarelo ',
    value: '',
},
{
    id: '7',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Roxo',
    value: '',
},
{
    id: '8',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Verde Lima ',
    value: '',
},
{
    id: '9',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Verde',
    value: '',
},
{
    id: '10',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Azul Claro ',
    value: '',
},
{
    id: '11',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Marrom ',
    value: '',
},



//Chikara
{
    id: '12',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Branco ',
    value: '',
},
{
    id: '13',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Preto ',
    value: '',
},
{
    id: '14',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Vermelho ',
    value: '',
},
{
    id: '15',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Azul Claro ',
    value: '',
},
{
    id: '16',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Azul ',
    value: '',
},
{
    id: '17',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Rosa ',
    value: '',
},
{
    id: '18',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Verde ',
    value: '',
},
{
    id: '19',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Verde Lima ',
    value: '',
},
{
    id: '20',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Marrom ',
    value: '',
},
{
    id: '21',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Laranja  ',
    value: '',
},
{
    id: '22',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Roxo ',
    value: '',
},
{
    id: '23',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Cinza',
    value: '',
},

//Camoflagem Liquida
{
    id: '24',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Branco',
    value: '',
},
{
    id: '25',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Preto ',
    value: '',
},
{
    id: '26',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Vermelho ',
    value: '',
},
{
    id: '27',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Azul ',
    value: '',
},
{
    id: '28',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Azul Claro ',
    value: '',
},
{
    id: '29',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Marrom ',
    value: '',
},
{
    id: '30',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Cinza ',
    value: '',
},
{
    id: '31',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Laranja ',
    value: '',
},
{
    id: '32',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Amarelo ',
    value: '',
},
{
    id: '33',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Roxo ',
    value: '',
},

//composto C
{
    id: '34',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Branco ',
    value: '',
},
{
    id: '35',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Preto ',
    value: '',
},
{
    id: '36',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Vermelho ',
    value: '',
},
{
    id: '37',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Azul ',
    value: '',
},
{
    id: '38',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Azul Claro  ',
    value: '',
},
{
    id: '11111',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Verde ',
    value: '',
},
{
    id: '11112',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Verde Lima ',
    value: '',
},
{
    id: '39',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Marrom ',
    value: '',
},
{
    id: '40',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Cinza ',
    value: '',
},
{
    id: '41',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Laranja ',
    value: '',
},
{
    id: '42',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Amarelo ',
    value: '',
},
{
    id: '43',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Roxo ',
    value: '',
},

//Luster Edge


{
    id: '44',
    image: './produtos img/luster ed.jpg',
    title: 'Adesivo Luster Edge',
    title1: 'Cor: Branco ',
    value: '',
},
{
    id: '45',
    image: './produtos img/luster ed.jpg',
    title: 'Adesivo Luster Edge',
    title1: 'Cor: Preto ',
    value: '',
},
{
    id: '46',
    image: './produtos img/luster ed.jpg',
    title: 'Adesivo Luster Edge',
    title1: 'Cor: Azul ',
    value: '',
},
{
    id: '47',
    image: './produtos img/luster ed.jpg',
    title: 'Adesivo Luster Edge',
    title1: 'Cor: Azul Claro ',
    value: '',
},
{
    id: '48',
    image: './produtos img/luster ed.jpg',
    title: 'Adesivo Luster Edge',
    title1: 'Cor: Verde ',
    value: '',
},
{
    id: '49',
    image: './produtos img/luster ed.jpg',
    title: 'Adesivo Luster Edge',
    title1: 'Cor: Verde Lima ',
    value: '',
},
{
    id: '50',
    image: './produtos img/luster ed.jpg',
    title: 'Adesivo Luster Edge',
    title1: 'Cor: Roxo ',
    value: '',
},
{
    id: '51',
    image: './produtos img/luster ed.jpg',
    title: 'Adesivo Luster Edge',
    title1: 'Cor: Laranja ',
    value: '',
},
{
    id: '52',
    image: './produtos img/luster ed.jpg',
    title: 'Adesivo Luster Edge',
    title1: 'Cor: Amarelo ',
    value: '',
},
{
    id: '53',
    image: './produtos img/luster ed.jpg',
    title: 'Adesivo Luster Edge',
    title1: 'Cor: Vermelho ',
    value: '',
},

//Patrulha Das Dunas

{
    id: '54',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Branco  ',
    value: '',
},
{
    id: '55',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Preto ',
    value: '',
},
{
    id: '56',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Vermelho ',
    value: '',
},
{
    id: '57',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Verde ',
    value: '',
},
{
    id: '58',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Verde Lima ',
    value: '',
},
{
    id: '59',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Azul ',
    value: '',
},
{
    id: '60',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Azul Claro ',
    value: '',
},
{
    id: '61',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Laranja ',
    value: '',
},
{
    id: '62',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Amarelo ',
    value: '',
},
{
    id: '63',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Roxo ',
    value: '',
},
{
    id: '64',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Cinza',
    value: '',
},
{
    id: '65',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Marrom ',
    value: '',
},

]