const produtos = [

    //Roda Blssm
    {
        id: '1',
        image: './produtos img/blss.png',
        title: 'Roda Blssm',
        title1: 'Cor: Branco ',
        value: '',
    },
    {
        id: '2',
        image: './produtos img/blss.png',
        title: 'Roda Blssm',
        title1: 'Cor: Preto',
        value: '',
    },
    {
        id: '3',
        image: './produtos img/blss.png',
        title: 'Roda Blssm',
        title1: 'Cor: Vermelho ',
        value: '',
    },
    {
        id: '4',
        image: './produtos img/blss.png',
        title: 'Roda Blssm',
        title1: 'Cor: Verde Lima',
        value: '',
    },
    {
        id: '5',
        image: './produtos img/blss.png',
        title: 'Roda Blssm',
        title1: 'Cor: Verde',
        value: '',
    },
    {
        id: '6',
        image: './produtos img/blss.png',
        title: 'Roda Blssm',
        title1: 'Cor: Azul ',
        value: '',
    },
    {
        id: '7',
        image: './produtos img/blss.png',
        title: 'Roda Blssm',
        title1: 'Cor: Azul Claro',
        value: '',
    },
    {
        id: '8',
        image: './produtos img/blss.png',
        title: 'Roda Blssm',
        title1: 'Cor: Marrom',
        value: '',
    },
    {
        id: '9',
        image: './produtos img/blss.png',
        title: 'Roda Blssm',
        title1: 'Cor: Rosa ',
        value: '',
    },
    {
        id: '10',
        image: './produtos img/blss.png',
        title: 'Roda Blssm',
        title1: 'Cor: Cinza',
        value: '',
    },
    {
        id: '11',
        image: './produtos img/blss.png',
        title: 'Roda Blssm',
        title1: 'Cor: Roxo ',
        value: '',
    },
    {
        id: '12',
        image: './produtos img/blss.png',
        title: 'Roda Blssm',
        title1: 'Cor: Amarelo ',
        value: '',
    },

//Roda Cyberware
    
    {
        id: '13',
        image: './produtos img/cyber.png',
        title: 'Roda Cyberware',
        title1:'Cor: Branco',
        value: '',
    },
    {
        id: '14',
        image: './produtos img/cyber.png',
        title: 'Roda Cyberware',
        title1:'Cor: Preto',
        value: '',
    },
    {
        id: '15',
        image: './produtos img/cyber.png',
        title: 'Roda Cyberware',
        title1:'Cor: Vermelho',
        value: '',
    },
    {
        id: '16',
        image: './produtos img/cyber.png',
        title: 'Roda Cyberware',
        title1:'Cor: Azul',
        value: '',
    },
    {
        id: '17',
        image: './produtos img/cyber.png',
        title: 'Roda Cyberware',
        title1:'Cor: Azul Claro',
        value: '',
    },
    {
        id: '18',
        image: './produtos img/cyber.png',
        title: 'Roda Cyberware',
        title1:'Cor: Rosa',
        value: '',
    },
    {
        id: '19',
        image: './produtos img/cyber.png',                                 
        title: 'Roda Cyberware',
        title1:'Cor: Laranja',
        value: '',
    },
    {
        id: '20',
        image: './produtos img/cyber.png',
        title: 'Roda Cyberware',
        title1:'Cor: Amarelo',
        value: '',
    },
    {
        id: '21',
        image: './produtos img/cyber.png',
        title: 'Roda Cyberware',
        title1:'Cor: Verde',
        value: '',
    },
    {
        id: '22',
        image: './produtos img/cyber.png',
        title: 'Roda Cyberware',
        title1:'Cor: Verde Claro',
        value: '',
    },
    {
        id: '23',
        image: './produtos img/cyber.png',
        title: 'Roda Cyberware',
        title1:'Cor: Cinza',
        value: '',
    },
    {
        id: '24',
        image: './produtos img/cyber.png',
        title: 'Roda Cyberware',
        title1:'Cor: Roxo',
        value: '',
    },


    //Roda Curto-Circuito
    
    {
        id: '25',
        image: './produtos img/curto.jpg',
        title: 'Roda Curto-Circuito',
        title1: 'Cor: Branco',
        value: '',
    },
    {
        id: '26',
        image: './produtos img/curto.jpg',
        title: 'Roda Curto-Circuito',
        title1: 'Cor: Preto',
        value: '',
    },
    {
        id: '27',
        image: './produtos img/curto.jpg',
        title: 'Roda Curto-Circuito',
        title1: 'Cor: Vermelho',
        value: '',
    },
    {
        id: '28',
        image: './produtos img/curto.jpg',
        title: 'Roda Curto-Circuito',
        title1: 'Cor: Azul',
        value: '',
    },
    {
        id: '29',
        image: './produtos img/curto.jpg',
        title: 'Roda Curto-Circuito',
        title1: 'Cor: Azul Claro',
        value: '',
    },
    {
        id: '30',
        image: './produtos img/curto.jpg',
        title: 'Roda Curto-Circuito',
        title1: 'Cor: Verde',
        value: '',
    },
    
    {
        id: '31',
        image: './produtos img/curto.jpg',
        title: 'Roda Curto-Circuito',
        title1: 'Cor: Verde Claro',
        value: '',
    },
    {
        id: '32',
        image: './produtos img/curto.jpg',
        title: 'Roda Curto-Circuito',
        title1: 'Cor: Rosa',
        value: '',
    },
    {
        id: '33',
        image: './produtos img/curto.jpg',
        title: 'Roda Curto-Circuito',
        title1: 'Cor: Marrom',
        value: '',
    },
    {
        id: '34',
        image: './produtos img/curto.jpg',
        title: 'Roda Curto-Circuito',
        title1: 'Cor: Roxa',
        value: '',
    },
    {
        id: '35',
        image: './produtos img/curto.jpg',
        title: 'Roda Curto-Circuito',
        title1: 'Cor: Laranja',
        value: '',
    },
    {
        id: '36',
        image: './produtos img/curto.jpg',
        title: 'Roda Curto-Circuito',
        title1: 'Cor: Cinza',
        value: '',
    },
    {
        id: '37',
        image: './produtos img/curto.jpg',
        title: 'Roda Curto-Circuito',
        title1: 'Cor: Amarelo ',
        value: '',
    },
    // Roda Dimonix
    {
        id: '38',
        image: './produtos img/dimonix.png',
        title: 'Roda Dimonix',
        title1: 'Cor: Branco',
        value: '',
    },
    {
        id: '39',
        image: './produtos img/dimonix.png',
        title: 'Roda Dimonix',
        title1: 'Cor: Preto',
        value: '',
    },
    {
        id: '40',
        image: './produtos img/dimonix.png',
        title: 'Roda Dimonix',
        title1: 'Cor: Vermelho',
        value: '',
    },
    {
        id: '41',
        image: './produtos img/dimonix.png',
        title: 'Roda Dimonix',
        title1: 'Cor: Azul',
        value: '',
    },
    {
        id: '43',
        image: './produtos img/dimonix.png',
        title: 'Roda Dimonix',
        title1: 'Cor: Azul Claro ',
        value: '',
    },
    {
        id: '44',
        image: './produtos img/dimonix.png',
        title: 'Roda Dimonix',
        title1: 'Cor: Verde',
        value: '',
    },
    {
        id: '45',
        image: './produtos img/dimonix.png',
        title: 'Roda Dimonix',
        title1: 'Cor: Verde Claro',
        value: '',
    },
    {
        id: '46',
        image: './produtos img/dimonix.png',
        title: 'Roda Dimonix',
        title1: 'Cor: Laranja',
        value: '',
    },
    {
        id: '47',
        image: './produtos img/dimonix.png',
        title: 'Roda Dimonix',
        title1: 'Cor: Marrom',
        value: '',
    },
    {
        id: '48',
        image: './produtos img/dimonix.png',
        title: 'Roda Dimonix',
        title1: 'Cor: Rosa',
        value: '',
    },
    {
        id: '49',
        image: './produtos img/dimonix.png',
        title: 'Roda Dimonix',
        title1: 'Cor: Roxo',
        value: '',
    },
    {
        id: '50',
        image: './produtos img/dimonix.png',
        title: 'Roda Dimonix',
        title1: 'Cor: Cinza',
        value: '',
    },
    {
        id: '51',
        image: './produtos img/dimonix.png',
        title: 'Roda dimonix',
        title1: 'Cor: Amarelo ',
        value: '',
    },
    
    //Roda Garoto-Músculos
    {
        id: '52',
        image: './produtos img/garoto.jpg',
        title: 'Roda Garoto-Músculos',
        title1: 'Cor: Branco',
        value: '',
    },
    {
        id: '53',
        image: './produtos img/garoto.jpg',
        title: 'Roda Garoto-Músculos',
        title1: 'Cor: Preto',
        value: '',
    },
    {
        id: '54',
        image: './produtos img/garoto.jpg',
        title: 'Roda Garoto-Músculos',
        title1: 'Cor: Vermelho',
        value: '',
    },
    {
        id: '55',
        image: './produtos img/garoto.jpg',
        title: 'Roda Garoto-Músculos',
        title1: 'Cor: Azul',
        value: '',
    },
    {
        id: '56',
        image: './produtos img/garoto.jpg',
        title: 'Roda Garoto-Músculos',
        title1: 'Cor: Azul Claro',
        value: '',
    },
    {
        id: '57',
        image: './produtos img/garoto.jpg',
        title: 'Roda Garoto-Músculos',
        title1: 'Cor: Verde',
        value: '',
    },
    {
        id: '58',
        image: './produtos img/garoto.jpg',
        title: 'Roda Garoto-Músculos',
        title1: 'Cor: Verde Claro',
        value: '',
    },
    {
        id: '59',
        image: './produtos img/garoto.jpg',
        title: 'Roda Garoto-Músculos',
        title1: 'Cor: Roxo',
        value: '',
    },
    {
        id: '60',
        image: './produtos img/garoto.jpg',
        title: 'Roda Garoto-Músculos',
        title1: 'Cor: Rosa',
        value: '',
    },
    
    {
        id: '61',
        image: './produtos img/garoto.jpg',
        title: 'Roda Garoto-Músculos',
        title1: 'Cor: Laranja',
        value: '',
    },
    {
        id: '62',
        image: './produtos img/garoto.jpg',
        title: 'Roda Garoto-Músculos',
        title1: 'Cor: Marrom',
        value: '',
    },
    {
        id: '63',
        image: './produtos img/garoto.jpg',
        title: 'Roda Garoto-Músculos',
        title1: 'Cor: Cinza',
        value: '',
    },
    {
        id: '64',
        image: './produtos img/garoto.jpg',
        title: 'Roda Garoto-Músculos',
        title1: 'Cor: Amarelo ',
        value: '',
    },
    
//Roda Hamster

    {
        id: '65',
        image: './produtos img/hamster.png',
        title: 'Roda Hamster',
        title1: 'Cor: Branco',
        value: '',
    },
    {
        id: '66',
        image: './produtos img/hamster.png',
        title: 'Roda Hamster',
        title1: 'Cor: Preto',
        value: '',
    },
    {
        id: '67',
        image: './produtos img/hamster.png',
        title: 'Roda Hamster',
        title1: 'Cor: Vermelho',
        value: '',
    },
    {
        id: '68',
        image: './produtos img/hamster.png',
        title: 'Roda Hamster',
        title1: 'Cor: Verde',
        value: '',
    },
    {
        id: '69',
        image: './produtos img/hamster.png',
        title: 'Roda Hamster',
        title1: 'Cor: Verde Claro',
        value: '',
    },
    {
        id: '70',
        image: './produtos img/hamster.png',
        title: 'Roda Hamster',
        title1: 'Cor: Azul',
        value: '',
    },
    {
        id: '71',
        image: './produtos img/hamster.png',
        title: 'Roda Hamster',
        title1: 'Cor: Azul Claro',
        value: '',
    },
    {
        id: '72',
        image: './produtos img/hamster.png',
        title: 'Roda Hamster',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '73',
        image: './produtos img/hamster.png',
        title: 'Roda Hamster',
        title1: 'Cor: Roxo',
        value: '',
    },
    {
        id: '74',
        image: './produtos img/hamster.png',
        title: 'Roda Hamster',
        title1: 'Cor: Rosa',
        value: '',
    },
    {
        id: '75',
        image: './produtos img/hamster.png',
        title: 'Roda Hamster',
        title1: 'Cor: Marrom',
        value: '',
    },
    {
        id: '76',
        image: './produtos img/hamster.png',
        title: 'Roda Hamster',
        title1: 'Cor: Cinza',
        value: '',
    },
    {
        id: '77',
        image: './produtos img/hamster.png',
        title: 'Roda Hamster',
        title1: 'Cor: Amarelo ',
        value: '',
    },
    
//Roda Helicoprion

    {
        id: '78',
        image: './produtos img/heli.webp',
        title: 'Roda Helicoprion',
        title1: 'Cor: Branco',
        value: '',
    },
    {
        id: '79',
        image: './produtos img/heli.webp',
        title: 'Roda Helicoprion',
        title1: 'Cor: Preto',
        value: '',
    },
    {
        id: '80',
        image: './produtos img/heli.webp',
        title: 'Roda Helicoprion',
        title1: 'Cor: Vermelho',
        value: '',
    },
    {
        id: '81',
        image: './produtos img/heli.webp',
        title: 'Roda Helicoprion',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '82',
        image: './produtos img/heli.webp',
        title: 'Roda Helicoprion',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '83',
        image: './produtos img/heli.webp',
        title: 'Roda Helicoprion',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '84',
        image: './produtos img/heli.webp',
        title: 'Roda Helicoprion',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '85',
        image: './produtos img/heli.webp',
        title: 'Roda Helicoprion',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '86',
        image: './produtos img/heli.webp',
        title: 'Roda Helicoprion',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '87',
        image: './produtos img/heli.webp',
        title: 'Roda Helicoprion',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '88',
        image: './produtos img/heli.webp',
        title: 'Roda Helicoprion',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '89',
        image: './produtos img/heli.webp',
        title: 'Roda Helicoprion',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '90',
        image: './produtos img/heli.webp',
        title: 'Roda Helicoprion',
        title1: 'Cor: Amarelo ',
        value: '',
    },
    
//Roda Mandala

    {
        id: '91',
        image: './produtos img/mandala.jpg',
        title: 'Roda Mandala',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '92',
        image: './produtos img/mandala.jpg',
        title: 'Roda Mandala',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '93',
        image: './produtos img/mandala.jpg',
        title: 'Roda Mandala',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '94',
        image: './produtos img/mandala.jpg',
        title: 'Roda Mandala',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '95',
        image: './produtos img/mandala.jpg',
        title: 'Roda Mandala',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '96',
        image: './produtos img/mandala.jpg',
        title: 'Roda Mandala',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '97',
        image: './produtos img/mandala.jpg',
        title: 'Roda Mandala',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '98',
        image: './produtos img/mandala.jpg',
        title: 'Roda Mandala',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '99',
        image: './produtos img/mandala.jpg',
        title: 'Roda Mandala',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '100',
        image: './produtos img/mandala.jpg',
        title: 'Roda Mandala',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '101',
        image: './produtos img/mandala.jpg',
        title: 'Roda Mandala',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '102',
        image: './produtos img/mandala.jpg',
        title: 'Roda Mandala',
        title1: 'Cor: ',
        value: '',
    },
    {
        id: '103',
        image: './produtos img/mandala.jpg',
        title: 'Roda Mandala',
        title1: 'Cor: Amarelo ',
        value: '',
    },
]