const produtos = [

//Harbinger

{
    id: '1',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Branco ',
    value: '50',
    title3: 'harbinger gxt',
},
{
    id: '2',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Preto',
    value: '',
    title3: 'harbinger gxt',
},
{
    id: '3',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Azul ',
    value: '20',
    title3: 'harbinger gxt',
},
{
    id: '4',
    image: './produtos img/hanbi.png',                                
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Rosa',
    value: '20',
    title3: 'harbinger gxt',
},
{
    id: '5',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Vermelho ',
    value: '20',
    title3: 'harbinger gxt',
},
{
    id: '6',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Amarelo ',
    value: '20',
    title3: 'harbinger gxt',
},
{
    id: '7',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Roxo',
    value: '20',
    title3: 'harbinger gxt',
},
{
    id: '8',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Verde Claro ',
    value: '20',
    title3: 'harbinger gxt',
},
{
    id: '9',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Verde',
    value: '20',
    title3: 'harbinger gxt',
},
{
    id: '10',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Azul Claro ',
    value: '20',
    title3: 'harbinger gxt',
},
{
    id: '11',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Marrom ',
    value: '20',
    title3: 'harbinger gxt',
},
{
    id: '-2',
    image: './produtos img/hanbi.png',
    title: 'Carro Harbinger GXT',
    title1: 'Cor: Cinza ',
    value: '20',
    title3: 'harbinger gxt',
},


//Chikara
{
    id: '12',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Branco ',
    value: '150',
    title3: 'chikara gxt',
},
{
    id: '13',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Preto ',
    value: '',
    title3: 'chikara gxt',
},
{
    id: '14',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Vermelho ',
    value: '50',
    title3: 'chikara gxt',
},
{
    id: '15',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Azul Claro ',
    value: '50',
    title3: 'chikara gxt',
},
{
    id: '16',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Azul ',
    value: '50',
    title3: 'chikara gxt',
},
{
    id: '17',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Rosa ',
    value: '50',
    title3: 'chikara gxt',
},
{
    id: '18',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Verde ',
    value: '50',
    title3: 'chikara gxt',
},
{
    id: '19',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Verde Claro ',
    value: '50',
    title3: 'chikara gxt',
},
{
    id: '20',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Marrom ',
    value: '50',
    title3: 'chikara gxt',
},
{
    id: '21',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Laranja  ',
    value: '50',
    title3: 'chikara gxt',
},
{
    id: '22',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Roxo ',
    value: '50',
    title3: 'chikara gxt',
},
{
    id: '23',
    image: './produtos img/chika.webp',
    title: ' Carro Chikara GXT',
    title1: 'Cor: Cinza',
    value: '50',
    title3: 'chikara gxt',
},
{
    id: '24',
    image: './produtos img/chika.webp',
    title: 'Carro Chikara GXT',
    title1: 'Cor: Amarelo ',
    value: '50',
    title3: 'chikara gxt',
},


//Camoflagem Liquida
{
    id: '25',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Branco',
    value: '50',
    title3: 'camo liquida',
},
{
    id: '26',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Preto ',
    value: '',
    title3: 'camo liquida',
},
{
    id: '27',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Vermelho ',
    value: '50',
    title3: 'camo liquida',
},
{
    id: '28',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Azul ',
    value: '50',
    title3: 'camo liquida',
},
{
    id: '29',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Azul Claro ',
    value: '20',
    title3: 'camo liquida',
},
{
    id: '30',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Verde ',
    value: '20',
    title3: 'camo liquida',
},
{
    id: '31',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Verde Claro ',
    value: '20',
    title3: 'camo liquida',
},
{
    id: '32',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Marrom ',
    value: '20',
    title3: 'camo liquida',
},
{
    id: '33',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Rosa',
    value: '30',
    title3: 'camo liquida',
},
{
    id: '34',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Cinza ',
    value: '10',
    title3: 'camo liquida',
},
{
    id: '35',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Laranja ',
    value: '20',  
    title3: 'camo liquida',                                                                   
},
{
    id: '36',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Amarelo ',
    value: '20',
    title3: 'camo liquida',
},
{
    id: '37',
    image: './produtos img/coma liquida.jpg',
    title: 'Adesivo Camo Liquida',
    title1: 'Cor: Roxo ',
    value: '30',
    title3: 'camo liquida',
},

//composto C
{
    id: '38',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Branco ',
    value: '50',
    title3: 'composto c',
},
{
    id: '40',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Preto ',
    value: '50',
    title3: 'composto c',
},
{
    id: '41',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Vermelho ',
    value: '20',
    title3: 'composto c',
},
{
    id: '42',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Azul ',
    value: '20',
    title3: 'composto c',
},
{
    id: '43',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Azul Claro  ',
    value: '20',
    title3: 'composto c',
},
{
    id: '44',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Verde ',
    value: '20',
    title3: 'composto c',
},
{
    id: '45',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Verde Claro ',
    value: '20',
    title3: 'composto c',
},
{
    id: '46',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Marrom ',
    value: '20',
    title3: 'composto c',
},
{
    id: '47',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Rosa',
    value: '20',
    title3: 'composto c',
},
{
    id: '48',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Cinza ',
    value: '20',
    title3: 'composto c',
},
{                                                                        
    id: '49',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Laranja ',
    value: '20',
    title3: 'composto c',
},
{
    id: '50',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Amarelo ',
    value: '20',
    title3: 'composto c',
},
{
    id: '51',
    image: './produtos img/compoc.jpg',
    title: 'Adesivo Composto C',
    title1: 'Cor: Roxo ',
    value: '20',
    title3: 'composto c',
},

//Luster Edge


{
    id: '52',
    image: './produtos img/luster ed.jpg',
    title: 'Adesivo Luster Edge',
    title1: 'Cor: Branco ',
    value: '120',
    title3: 'luster edge',
},
{
    id: '53',
    image: './produtos img/luster ed.jpg',
    title: 'Adesivo Luster Edge',
    title1: 'Cor: Preto ',
    value: '',
    title3: 'luster edge',
},
{
    id: '54',
    image: './produtos img/luster ed.jpg',
    title: 'Adesivo Luster Edge',
    title1: 'Cor: Azul ',
    value: '50',
    title3: 'luster edge',
},
{
    id: '55',
    image: './produtos img/luster ed.jpg',
    title: 'Adesivo Luster Edge',
    title1: 'Cor: Azul Claro ',
    value: '30',
    title3: 'luster edge',
},
{
    id: '56',
    image: './produtos img/luster ed.jpg',
    title: 'Adesivo Luster Edge',
    title1: 'Cor: Verde ',
    value: '50',
    title3: 'luster edge',
},
{
    id: '57',
    image: './produtos img/luster ed.jpg',
    title: 'Adesivo Luster Edge',
    title1: 'Cor: Verde Claro ',
    value: '50',
    title3: 'luster edge',
},
{
    id: '58',
    image: './produtos img/luster ed.jpg',
    title: 'Adesivo Luster Edge',
    title1: 'Cor: Roxo ',
    value: '50',
    title3: 'luster edge',
},
{
    id: '59',
    image: './produtos img/luster ed.jpg',
    title: 'Adesivo Luster Edge',
    title1: 'Cor: Laranja ',
    value: '50',
    title3: 'luster edge',
},                                                                           
{
    id: '60',
    image: './produtos img/luster ed.jpg',
    title: 'Adesivo Luster Edge',
    title1: 'Cor: Rosa',
    value: '50',
    title3: 'luster edge',
},
{
    id: '61',
    image: './produtos img/luster ed.jpg',
    title: 'Adesivo Luster Edge',
    title1: 'Cor: Amarelo ',
    value: '30',
    title3: 'luster edge',
},
{
    id: '62',
    image: './produtos img/luster ed.jpg',
    title: 'Adesivo Luster Edge',
    title1: 'Cor: Vermelho ',
    value: '50',
    title3: 'luster edge',
},

//Patrulha Das Dunas

{
    id: '63',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Branco  ',
    value: '50',
    title3: 'patrulha das dunas',
},
{
    id: '64',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Preto ',
    value: '50',
    title3: 'patrulha das dunas',
},
{
    id: '65',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Vermelho ',
    value: '30',
    title3: 'patrulha das dunas',
},
{
    id: '66',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Verde ',
    value: '20',
    title3: 'patrulha das dunas',
},
{
    id: '67',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Verde Claro ',
    value: '30',
    title3: 'patrulha das dunas',
},
{
    id: '68',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Azul ',
    value: '30',
    title3: 'patrulha das dunas',
},
{
    id: '69',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Azul Claro ',
    value: '30',
    title3: 'patrulha das dunas',
},
{
    id: '70',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',                                      
    title1: 'Cor: Laranja ',
    value: '30',
    title3: 'patrulha das dunas',
},
{
    id: '71',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Amarelo ',
    value: '20',
    title3: 'patrulha das dunas',
},
{
    id: '72',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Roxo ',
    value: '20',
    title3: 'patrulha das dunas',
},
{
    id: '-1',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: rosa ',
    value: '20',
    title3: 'patrulha das dunas',
},


{
    id: '74',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Cinza',
    value: '',
    title3: 'patrulha das dunas',
},
{
    id: '75',
    image: './produtos img/duna.jpg',
    title: ' Adesivo Patrulha Das Dunas',
    title1: 'Cor: Marrom ',
    value: '',
    title3: 'patrulha das dunas',
},

//Roda Jandertek

{
    id: '76',
    image: './produtos img/jandertek.png',
    title: 'Roda Jandertek',
    title1: 'Cor: Branco ',
    value: '50',
    title3: 'jandertek',
},
{
    id: '77',
    image: './produtos img/jandertek.png',
    title: 'Roda Jandertek',
    title1: 'Cor: Preto',
    value: '20',
    title3: 'jandertek',
},
{
    id: '78',
    image: './produtos img/jandertek.png',
    title: 'Roda Jandertek',
    title1: 'Cor: Azul',
    value: '20',
    title3: 'jandertek',
},
{
    id: '79',
    image: './produtos img/jandertek.png',
    title: 'Roda Jandertek',
    title1: 'Cor: Azul Claro',
    value: '',
    title3: 'jandertek',
},
{
    id: '80',
    image: './produtos img/jandertek.png',
    title: 'Roda Jandertek',
    title1: 'Cor: Vermelho ',
    value: '20',
    title3: 'jandertek',
},
{
    id: '81',
    image: './produtos img/jandertek.png',
    title: 'Roda Jandertek',
    title1: 'Cor: Verde',
    value: '20',
    title3: 'jandertek',
},
{
    id: '82',
    image: './produtos img/jandertek.png',
    title: 'Roda Jandertek',
    title1: 'Cor: Verde Claro ',
    value: '20',
    title3: 'jandertek',
},
{
    id: '83',
    image: './produtos img/jandertek.png',
    title: 'Roda Jandertek',
    title1: 'Cor: Laraja',
    value: '20',
    title3: 'jandertek',
},
{
    id: '84',
    image: './produtos img/jandertek.png',
    title: 'Roda Jandertek',
    title1: 'Cor: Rosa',
    value: '20',
    title3: 'jandertek',
},
{
    id: '85',
    image: './produtos img/jandertek.png',
    title: 'Roda Jandertek',
    title1: 'Cor: Roxo',
    value: '30',
    title3: 'jandertek',
},
{
    id: '86',
    image: './produtos img/jandertek.png',
    title: 'Roda Jandertek',
    title1: 'Cor: Cinza ',
    value: '20',
    title3: 'jandertek',
},
{
    id: '87',
    image: './produtos img/jandertek.png',
    title: 'Roda Jandertek',
    title1: 'Cor: Amarelo ',
    value: '20',
    title3: 'jandertek',
},



//Roda Hélice

{
    id: '88',
    image: './produtos img/helice.jpg',
    title: 'Roda Hélice',
    title1: 'Cor: Branco',
    value: '50',
    title3: 'hélice',
},
{
    id: '89',
    image: './produtos img/helice.jpg',
    title: 'Roda Hélice',
    title1: 'Cor: Preto',
    value: '30',
    title3: 'hélice',
},
{
    id: '90',
    image: './produtos img/helice.jpg',
    title: 'Roda Hélice',
    title1: 'Cor: Vermelho',
    value: '20',
    title3: 'hélice',
},
{
    id: '91',
    image: './produtos img/helice.jpg',
    title: 'Roda Hélice',
    title1: 'Cor: Azul',
    value: '20',
    title3: 'hélice',
},
{
    id: '92',
    image: './produtos img/helice.jpg',
    title: 'Roda Hélice',
    title1: 'Cor: Azul Claro',
    value: '20',
    title3: 'hélice',
},
{
    id: '93',
    image: './produtos img/helice.jpg',
    title: 'Roda Hélice',
    title1: 'Cor: Vermelho',
    value: '20',
    title3: 'hélice',
},
{
    id: '94',
    image: './produtos img/helice.jpg',
    title: 'Roda Hélice',
    title1: 'Cor: Verde',
    value: '20',
    title3: 'hélice',
},
{
    id: '95',
    image: './produtos img/helice.jpg',
    title: 'Roda Hélice',
    title1: 'Cor: Verde Claro',
    value: '20',
    title3: 'hélice',
},
{
    id: '96',
    image: './produtos img/helice.jpg',
    title: 'Roda Hélice',
    title1: 'Cor: Marrom',
    value: '20',
    title3: 'hélice',
},
{
    id: '97',
    image: './produtos img/helice.jpg',
    title: 'Roda Hélice',
    title1: 'Cor: Laranja',
    value: '20',
    title3: 'hélice',
},
{
    id: '98',
    image: './produtos img/helice.jpg',
    title: 'Roda Hélice',
    title1: 'Cor: Rosa',
    value: '20',
    title3: 'hélice',
},
{
    id: '99',
    image: './produtos img/helice.jpg',
    title: 'Roda Hélice',
    title1: 'Cor: Cinza',
    value: '20',
    title3: 'hélice',
},
{
    id: '100',
    image: './produtos img/helice.jpg',
    title: 'Roda Hélice',
    title1: 'Cor: Amarelo ',
    value: '20',
    title3: 'hélice',
},


//Roda Holosphere

{
    id: '101',
    image: './produtos img/holos.png',
    title: 'Roda Holosphere',
    title1: 'Cor: Branco',
    value: '100',
    title3: 'holosphere',
},
{
    id: '102',
    image: './produtos img/holos.png',
    title: 'Roda Holosphere',
    title1: 'Cor: Preto',
    value: '50',
    title3: 'holosphere',
},
{
    id: '103',
    image: './produtos img/holos.png',
    title: 'Roda Holosphere',
    title1: 'Cor: Vermelho',
    value: '50',
    title3: 'holosphere',
},
{
    id: '104',
    image: './produtos img/holos.png',
    title: 'Roda Holosphere',
    title1: 'Cor: Azul',
    value: '20',
    title3: 'holosphere',
},
{
    id: '105',
    image: './produtos img/holos.png',                               
    title: 'Roda Holosphere',
    title1: 'Cor: Azul Claro',
    value: '50',
    title3: 'holosphere',
},
{
    id: '106',
    image: './produtos img/holos.png',
    title: 'Roda Holosphere',
    title1: 'Cor: Verde ',
    value: '30',
    title3: 'holosphere',
},
{
    id: '107',
    image: './produtos img/holos.png',
    title: 'Roda Holosphere',
    title1: 'Cor: Verde Claro',
    value: '50',
    title3: 'holosphere',
},
{
    id: '108',
    image: './produtos img/holos.png',
    title: 'Roda Holosphere',
    title1: 'Cor: Marrom',
    value: '50',
    title3: 'holosphere',
},
{
    id: '109',
    image: './produtos img/holos.png',
    title: 'Roda Holosphere',
    title1: 'Cor: Laranja',
    value: '20',
    title3: 'holosphere',
},
{
    id: '110',
    image: './produtos img/holos.png',
    title: 'Adesivo Holosphere', 
    title1: 'Cor: Rosa',
    value: '50',
    title3: 'holosphere',
},
{
    id: '111',
    image: './produtos img/holos.png',
    title: 'Roda Holosphere',
    title1: 'Cor: Roxo',
    value: '50',
    title3: 'holosphere',
},
{
    id: '112',
    image: './produtos img/holos.png',
    title: 'Roda Holosphere',
    title1: 'Cor: Cinza',
    value: '50',
    title3: 'holosphere',
},
{
    id: '113',
    image: './produtos img/holos.png',
    title: 'Roda Holosphere',
    title1: 'Cor: Amarelo ',
    value: '20',
    title3: 'holosphere',
},


]